# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19V4DmxOKDqXzzTmZ7FrYuOB6RQgxMK4W
"""

#JavaScript object notation.

import json

x={"name": "Mohd Shanu",  "age":21,   "number":2222}
k=json.dumps(x)
print(type(k))

x='{"name": "Mohd Shanu",  "age":21,   "number":2222}'
m=json.loads(x)
print(type(m))

# Dumps Method...

import json
dic={ "name":"hii",
    "status":"byeee",
    "reply":"both"
}
   
js=json.dumps(dic ,separators =(".", " = "),)
print(js)
print(type(js))

# ListComprehension...

name=["Shanu","moizamam","Ravi","Aman"]
name1=[x.upper() for x in name]
name2=[x for x in name if "i" in x]
name3=["hello" for x in name]
name4=[x if x!= "Shanu" else "moizamam" for x in name]

print(name1)
print(name2)
print(name3)
print(name4)

# Exception handling.....
x = -1

if x < 0:
  raise Exception("Sorry, no numbers below zero")

# Random Function....

from numpy import random
s=random.randint([2,10,5,7,8],size=(2,5))
print(s)

import random
s=random.randint(5,10)
print(s)

# uses of Exception block....
try:
  num=int(input("enter the number"))
  a=[2,3,54]
  print(a[num]) #num is the index value
except ValueError:
  print("number enter is not an integer")#throw error when enterd value is not integer 
except IndexError:
  print("Invalid Error") #throw error when the value of num is out of index
else:
  print("run only when try is correct")  #there is no error

finally:
  print("don't worry i will rum always ")